version: '3.8'

services:
  # CPU-based deployment (default)
  multimodal-sentiment-api:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - API_WORKERS=4
      - DEVICE=cpu
      - ENABLE_GPU=false
      - MAX_FILE_SIZE_AUDIO=52428800
      - MAX_FILE_SIZE_VIDEO=52428800
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs:rw
      - ./models:/app/models:rw
      - ./config:/app/config:ro
      - ./.env:/app/.env:ro
      - ./test_files:/app/test_files:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
    networks:
      - sentiment-network
    profiles:
      - cpu

  # GPU-enabled deployment (optional)
  multimodal-sentiment-api-gpu:
    build:
      context: .
      target: gpu
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - API_WORKERS=2
      - DEVICE=cuda
      - ENABLE_GPU=true
      - CUDA_VISIBLE_DEVICES=0
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
      - ./config:/app/config
      - ./.env:/app/.env
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          cpus: '4.0'
          memory: 8G
    networks:
      - sentiment-network
    profiles:
      - gpu

  # Development environment
  multimodal-sentiment-dev:
    build:
      context: .
      target: production
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - API_WORKERS=1
      - DEBUG=true
      - RELOAD=true
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./models:/app/models
      - ./config:/app/config
    command: ["python", "-m", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - sentiment-network
    profiles:
      - dev

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - multimodal-sentiment-api
    restart: unless-stopped
    networks:
      - sentiment-network
    profiles:
      - production

networks:
  sentiment-network:
    driver: bridge

volumes:
  logs:
  models:
  config:
